### ISSUE TITLE
Current falsch

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.schoolfree#10]
Heute am Sonntag, den 5.4., wird im Datenpunkt "current" bereits die Osterferien, die erst am 6.4. anfangen angezeigt. Richtig wäre "none".

Das Flag "today" ist korrekt auf false.

**Comment by simatec** [comment]
Danke für die Info. Welche Version läuft aktuell bei dir?

**Comment by Marty56** [comment]
0.5.1

**Comment by simatec** [comment]
Hab ich angeschaut und ist so gewollt. 
Da die Ferien heute starten und es z.B. für Rollläden etc. wichtig ist, ob am nächsten Tag frei ist, wird hier bereits der aktuelle Ferienstatus gesetzt und "tomorrow" wird auf true gesetzt.

**Comment by Marty56** [comment]
Ok. Verstehe die Begründung zwar nicht und habe den Eindruck, dass u.U. meine Fehlermeldung nicht richtig verstanden wurde, aber das Thema ist auch wirklich nicht so wichtig, um sich länger damit zu beschäftigen.

**Comment by simatec** [comment]
> Heute am Sonntag, den 5.4., wird im Datenpunkt "current" bereits die Osterferien, die erst am 6.4. anfangen angezeigt. Richtig wäre "none".
> 
> Das Flag "today" ist korrekt auf false.

Doch habe es schon vertsanden ... Die Osterferien wurden bereits am Sonntag angezeigt, obwohl sie erst ab Montag starten.
Das hat damit zu tun, dass bereits "tomorrow" auf true ist, da für das setzen von Heizungssteuerungen und Rollladenzeiten dies ggfs. interessant sein könnte.

Beispiel:
Da am nächsten Tag Ferien sind, bleiben die Kids länger wach und die Heizung muss in ihrem Zimmer länger laufen oder der Rollladen soll dadurch später runterfahren.
Das sind Dinge, die dann auch schon einen Tag vor den Ferien greifen sollten.
