### ISSUE TITLE
Feiertage setzen "schoolfree.0.info.tomorrow" nicht auf true

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.schoolfree#11]
Man kann natürlich diskutierten, ob ein Feiertag ein Ferientag ist. Aber m.M. ist es sinnvoll einen Nicht -Schultag als Ferientag zu markieren.

**Comment by simatec** [comment]
Hast du in den Einstellungen die Feiertage aktiviert? Bzw. deaktiviert, dass Feiertage ignoriert werden sollen?

![image](https://user-images.githubusercontent.com/39792461/80726852-41027980-8b05-11ea-8448-40a4b89aa8c9.png)

**Comment by Marty56** [comment]
Ich habe die Checkbox mit der für mich verwirrenden Titel, deaktiviert.

**Comment by Marty56** [comment]
Habe jetzt aktiviert und den Adapter neu gestartet. Es wird immer noch false für morgen angezeigt.

**Comment by Marty56** [comment]
Ich habe mir jetzt in meinem Script ein Bugfix Workaround gebaut.
`
// ------------ Workaround für 'schoolfree.0.info.tomorrow' bug in schoolfree ----
    var tomorrow_school_free = getState('schoolfree.0.info.tomorrow').val;
    if (tomorrow_school_free == false) {
        var  nextstart_str = getState("schoolfree.0.info.next.start").val.split(".");
        var  nextstart    = new Date(nextstart_str[2] + "-" + nextstart_str[1] + "-" + nextstart_str[0]);
        nextstart.setHours(0,0,0,0);
        var tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        tomorrow.setHours(0,0,0,0);
        if (tomorrow === nextstart) tomorrow_school_free = true;
    }

`

**Comment by simatec** [comment]
Ich werde das die nächsten Tage fixen.

**Comment by Marty56** [comment]
Ich habe die Änderungen in dem Code gefixt und einen Vorschlag dazu gemacht. Bin aber mit dem GitHub nicht so vertraut. Kannst Du meinen Fix sehen?

**Comment by simatec** [comment]
Wurde mit Release 0.6.0 gefixt
