### ISSUE TITLE
falls morgen ein Ferientag oder Ferien beginnen wird info.current.start, end und name gesetzt

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.schoolfree#12]
Wenn morgen die Ferien beginnen oder Feiertag ist, sollten die Informationen dazu in "info.next" eingetragen werden und nicht in "info.current".
"info.current" ist n.m. Verständnis der Status des aktuellen Tags und nicht des morgigen, also zukünftigen Tags.

**Comment by simatec** [comment]
Wenn morgen die Ferien beginnen, bezieht sich dies schon auf die aktuellen Ferien.
next wären dann die folgenden Ferien ...

**Comment by Marty56** [comment]
Sorry die Logik kann ich nicht nachvollziehen. 

Wenn z.B. heute keine Ferien sind, dann sollte auch bei "current" kein Ferienname stehen, sondern bei next.
"current" -> laufende. Die Ferien laufen aber noch nicht, sondern erst morgen. 

Vielleicht solltest Du den Bug im Readme dokumentieren.

**Comment by simatec** [comment]
Das ist kein Bug, sondern so gewollt ...
Da die Regeln wie Rollladensteuerung, Heizung etc. Schon am Abend vorher greifen müssen, zählen hier dann auch die aktuellen Ferien. Das am heutigen Tage keine Ferien sind, sondern erst morgen sieht man daran, dass today false ist und tomorow true

**Comment by Marty56** [comment]
Das ist dann leider gewollter Nonsense. 
Aber in einer Meritokratie kann man wohl seine "Logik" implementieren wie man will. :-(

**Comment by simatec** [comment]
Das werde ich nicht weiter kommentieren. Der Issue ist geschlossen ...
