### ISSUE TITLE
schoolfree set state error: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by darkman242** [simatec/ioBroker.schoolfree#15]
ich bekomme regelmäßig folgende Warnung im Log.

schoolfree.0 | 2020-05-25 08:08:16.894 | debug | (4817) Plugin sentry destroyed
-- | -- | -- | --
schoolfree.0 | 2020-05-25 08:08:16.850 | debug | (4817) cleaned everything up...
schoolfree.0 | 2020-05-25 08:07:56.850 | info | (4817) schoolfree request done
schoolfree.0 | 2020-05-25 08:07:56.848 | debug | (4817) ignore public holiday
schoolfree.0 | 2020-05-25 08:07:56.817 | warn | (4817) schoolfree set state error: TypeError: Cannot read property 'name' of undefined
schoolfree.0 | 2020-05-25 08:07:56.816 | debug | (4817) counties number:
schoolfree.0 | 2020-05-25 08:07:56.446 | info | (4817) starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.schoolfree, node: v12.16.3, js-controller: 3.1.4
schoolfree.0 | 2020-05-25 08:07:56.362 | debug | (4817) Plugin sentry Initialize Plugin (enabled=true)
schoolfree.0 | 2020-05-25 08:07:54.832 | debug | (4817) statesDB connected
schoolfree.0 | 2020-05-25 08:07:54.832 | debug | (4817) States connected to redis: 127.0.0.1:9000
schoolfree.0 | 2020-05-25 08:07:54.825 | debug | (4817) States create System PubSub Client
schoolfree.0 | 2020-05-25 08:07:54.824 | debug | (4817) States create User PubSub Client
schoolfree.0 | 2020-05-25 08:07:54.820 | debug | (4817) Redis States: Use Redis connection: 127.0.0.1:9000
schoolfree.0 | 2020-05-25 08:07:54.820 | debug | (4817) objectDB connected
schoolfree.0 | 2020-05-25 08:07:54.818 | debug | (4817) Objects connected to redis: 127.0.0.1:9001
schoolfree.0 | 2020-05-25 08:07:54.808 | debug | (4817) Objects client initialize lua scripts
schoolfree.0 | 2020-05-25 08:07:54.808 | debug | (4817) Objects create User PubSub Client
schoolfree.0 | 2020-05-25 08:07:54.807 | debug | (4817) Objects create System PubSub Client
schoolfree.0 | 2020-05-25 08:07:54.806 | debug | (4817) Objects client ready ... initialize now
schoolfree.0 | 2020-05-25 08:07:54.794 | debug | (4817) Redis Objects: Use Redis connection: 127.0.0.1:9001

iobroker 3.1.4, nodejs 12.16.3, npm 6.14.4, Debian 10 (VM) unter Proxmox

**Comment by simatec** [comment]
Kannst du mir bitte noch Info geben, welcher Name nicht gesetzt wird? 
Aktuelle Ferien oder die nächsten Ferien?
Zeige mal bitte deine Datenpunkte ...

**Comment by darkman242** [comment]
sieht für mich aus als wären alle DPs gefüllt, trotzdem kommt die Meldung
![image](https://user-images.githubusercontent.com/46793576/82789431-8f880700-9e6a-11ea-9413-840e746333dd.png)

**Comment by simatec** [comment]
Das sind nicht die Datenpunkte von schoolfree

**Comment by darkman242** [comment]
sorry :-)
![image](https://user-images.githubusercontent.com/46793576/82789684-002f2380-9e6b-11ea-9807-9ca73edebcaf.png)

**Comment by simatec** [comment]
OK, öffne bitte mal die Konfiguration von schollfree und speichere diese einmal neu ab.
Am besten mit einer neuen Auswahl, damit das speichern möglich wird.

Schaue mal, ob im Anschluß der Fehler noch immer auftritt ...

**Comment by darkman242** [comment]
Danke, hat funktioniert. Nun sind auch die DPs unter Location gefüllt.
