### ISSUE TITLE
no update of holidays

### ISSUE THREAD

**Issue by reutli** [simatec/ioBroker.schoolfree#17]
the actual version (0.5.0) is not updating holidays. we're having holidays in Baden-Würtemberg bout adapter is not showing them.

The latest version is working after filled out all filled in admin.

**Comment by simatec** [comment]
Kann ich leider nicht bestätigen ... 
Allerdings mit der Version 0.6.2 was die aktuellste ist getestet.

**Comment by reutli** [comment]
Hallo,

Richtig mit der neusten GitHub Version funktioniert es, nicht aber mit der stabile im Biobroker Repo
_____________________
Michael Reutlinger
Buchenweg 17
72415 Grosselfingen
T: +49 7476 914183
F: +49 7476 9145515

eMail: post@reutli.de

**Comment by robson80** [comment]
Hallo zusammen,

nach dem Update auf Version 0.6.3. erhalte ich ebenfalls Fehlermeldungen und die Instanz bricht jedes Mal nach dem Cronjob bzw. nach einem Neustart ab. Mit der vorherigen Version (0.6.2?) lief alles ohne Probleme.

Ich erhalte folgenden Fehler:

`
Quelle | Zeit | debug | Meldung
-- | -- | -- | --
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at IncomingMessage.emit (events.js:203:15)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Object.onceWrapper (events.js:286:20)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.schoolfree/node_modules/request/request.js:1076:12)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Request.emit (events.js:198:13)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.schoolfree/node_modules/request/request.js:1154:10)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Request.emit (events.js:198:13)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.schoolfree/node_modules/request/request.js:185:22)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.schoolfree/main.js:162:52)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at Array.filter (<anonymous>)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | at holidayNames.filter.d (/opt/iobroker/node_modules/iobroker.schoolfree/main.js:162:82)
schoolfree.0 | 2020-07-15 08:04:08.761 | error | (6083) TypeError: Cannot read property 'holiday_or_vacation_type_id' of undefined
schoolfree.0 | 2020-07-15 08:04:08.758 | error | (6083) uncaught exception: Cannot read property 'holiday_or_vacation_type_id' of undefined
`
