### ISSUE TITLE
Hinzufügen von weiteren Schulen

### ISSUE THREAD

**Issue by BlackPolo91** [simatec/ioBroker.schoolfree#175]
Ist es möglich eigenständig weitere Schulen hinzuzufügen ?

**Comment by simatec** [comment]
Nein … es können nur die Schulen genutzt werden, die in der API integriert sind.

**Comment by BlackPolo91** [comment]
Okay, woran liegt das ? Liefern nicht alle Schulen die benötigten Daten ? 😅

simatec ***@***.***> schrieb am Fr. 3. Feb. 2023 um 16:05:

**Comment by simatec** [comment]
Ja davon gehe ich aus. 
Man muss aber nicht zwingend eine Schule eintragen. 
Am Ende ist das Bundesland ausreichend, um den Adapter nutzen zu können.

**Comment by BlackPolo91** [comment]
Okay, vielen Dank 👍

simatec ***@***.***> schrieb am Fr. 3. Feb. 2023 um 16:09:
