### ISSUE TITLE
Himmelfahrtsferien --> Pfingstferien

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [simatec/ioBroker.schoolfree#189]
Ich bekomme für die nächsten Ferien in Bayern/Nürnberger Land *Himmelfahrtsferien* angezeigt. 
Der allgemeine Begriff ist *Pfingstferien*
Nicht dramatisch, sollte aber geändert werden - schließlich ist Himmelfahrt 10 Tage vor Pfingsten.

**Comment by simatec** [comment]
Bitte ein Issue bei der API aufmachen. Das hat nix mit dem Adapter zu tun
