### ISSUE TITLE
Aktualisiert nicht automatisch

### ISSUE THREAD

**Issue by floripappa** [simatec/ioBroker.schoolfree#195]
Die Instanz wird angeblich aktualisiert, 
![grafik](https://user-images.githubusercontent.com/118162433/235595855-e82d501b-7fad-44dd-9278-cdf4f0ef23e2.png)

aber die Objektwerte werden nicht geändert.
![grafik](https://user-images.githubusercontent.com/118162433/235596063-af925865-f1cb-486f-a459-d378d0789831.png)

**Comment by crunchip77** [comment]
schließe mich hier mal mit an, heut morgen(Donnerstag) sind die Rollo´s zu früh gefahren(diese Woche sind Ferien) Montag, Dienstag und Mittwoch funktionierte noch alles wie es soll
habe dann festgestellt, das die Datenpunkte unterhalb von current leer waren, erst nachdem die Instanz neu gestartet wurde, waren sie wieder korrekt befüllt.

sehe soeben im log
`<html>
<body>

schoolfree.0 | 2024-02-16 00:01:35.305 | info | Terminated (NO_ERROR): Without reason
-- | -- | -- | --
schoolfree.0 | 2024-02-16 00:01:05.292 | warn | schoolfree request error... API not reachable: AxiosError: Request failed with status code 500
schoolfree.0 | 2024-02-16 00:01:04.570 | info | starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.schoolfree, node: v18.19.1, js-controller: 5.0.19
host.IoBroker | 2024-02-16 00:01:00.040 | info | instance system.adapter.schoolfree.0 started with pid 1805643


</body>
</html>`
Daten sind aber vorhanden, mit Zeitstempel von Donnerstag
![image](https://github.com/simatec/ioBroker.schoolfree/assets/41550245/ed7df116-bb56-44c1-b39c-1ba43db0c926)

**Comment by simatec** [comment]
Dann war sicher keine Verbindung zur API... Ändere mal auf eine andere krumme Uhrzeit, damit die Server nicht überlastet sind.
