### ISSUE TITLE
Wrong next vacation

### ISSUE THREAD

**Issue by hgschiller** [simatec/ioBroker.schoolfree#20]
The adapter currently shows the summer vacation for NRW as the next vacation.
The following is displayed on the mehr-schulferien.de website:

![grafik](https://user-images.githubusercontent.com/78852559/114718336-3355fc00-9d36-11eb-8bbb-7c122e976445.png)

So the next vacation would be the Pfingstferien and not the Sommerferien.

In the JSON file https://www.mehr-schulferien.de/api/v2.0/periods I also find an entry for this holiday day:
			"ends_on": "2021-05-25",
			"holiday_or_vacation_type_id": 5,
			"id": 756,
			"is_public_holiday": false,
			"is_school_vacation": true,
			"is_valid_for_everybody": false,
			"is_valid_for_students": true,
			"location_id": 11,
			"starts_on": "2021-05-25",
			"updated_at": "2020-03-20T10:10:41"

**Comment by hgschiller** [comment]
I changed the following line (row 159) for testing:

old:    arrOnlyholiday = arrNewHoliday.filter(d => d.starts_on != d.ends_on);
new:  arrOnlyholiday = arrNewHoliday.filter(d => d.is_school_vacation == true);

With this change, it works fine!
However, I don't know if it might cause other errors.
Maybe you can check it out.

**Comment by simatec** [comment]
Unfortunately, I cannot recreate your problem. Here it is displayed correctly

![image](https://user-images.githubusercontent.com/39792461/117109776-7891aa80-ad85-11eb-9f97-ca3d2f3dbd82.png)

**Comment by ChristianPi99** [comment]
I have the same problem that the first vacation day of the X-Mas school break isn't flagged as today = true. Screenshot was taken on Dec 23 at 9am.
<img width="1149" alt="Bildschirm­foto 2022-12-23 um 08 58 01" src="https://user-images.githubusercontent.com/88233203/209543191-06888e65-49ba-437c-8113-1fc9f98e20b0.png">
