### ISSUE TITLE
Was ist zu tun , wenn die passende Schule nicht in der Auswahl ist ? 

### ISSUE THREAD

**Issue by aruttkamp** [simatec/ioBroker.schoolfree#200]
Wie kann ich eine Schule ( oder möglicherweise einen Kindergarten ) hinzufügen ? 
Ist das vorgesehen ?

**Comment by simatec** [comment]
Garnicht… der Adapter nutzt eine API und die gibt am Ende die Daten vor. 
Man muss auch keine Schule auswählen. Am Ende reicht das Bundesland.

**Comment by aruttkamp** [comment]
Ok. alles klar. dann kann ich auch die beweglichen Tage nirgendwo hinterlegen. 
Da würde ich dann tatsächlich drüber nachdenken ob ich das erweitere. Brauche es ab nächstem Schuljahr ;-) 
Danke für die Schnelle Antwort.

**Comment by simatec** [comment]
Bewegliche Ferientage müssen ebenfalls von der API kommen. In der Readme findest du alles zur API. Da müsstest du dort ein Issue aufmachen
