### ISSUE TITLE
Bewegliche Ferientag man. integrieren

### ISSUE THREAD

**Issue by Octopyrox** [simatec/ioBroker.schoolfree#218]
Hallo,

wäre es nicht ein tolles Feature, wenn man bewegliche Ferientage manuell hinzufügen könnte. Leider zeigt die Quellwebsite die nicht für unseren Kreis an und ich müsste das umständlicher über einen separaten Kalender realisieren, dann könnte ich aber auch gleich alle Ferien in den Kalender importieren.

Lässt sich eine manuelle Befüllung mit beweglichen Ferientagen noch integrieren?

Danke und viele Grüße

Markus

**Comment by simatec** [comment]
Der Adapter arbeitet mit der API von mehr-schulferien.de
Das Issue müsstet du dort öffnen.
https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues

**Comment by Octopyrox** [comment]
Hm, dachte wenn du eine manuelle Ergänzung einbaust, wird das eher was. Ich
glaub nicht, dass Mehr-Schulferien.de hier aktiv wird, werd's aber
probieren.

VG

Markus Dickel

Obermelsunger Str. 29
34212 Melsungen

Mobil: 01 73 - 57 33 73 9

simatec ***@***.***> schrieb am Mi., 4. Okt. 2023, 08:40:
