### ISSUE TITLE
Tägliche Fehlermeldung

### ISSUE THREAD

**Issue by mcn1** [simatec/ioBroker.schoolfree#231]
**Describe the bug**  
Ferien werden nicht automatisch aktualisiert. Wenn dann nur nach manuellem Neustart. 
Fehlermeldung:
schoolfree.0
2023-11-23 00:01:02.971	warn	schoolfree request holiday_or_vacation_types error: AxiosError: Request failed with status code 500

**To Reproduce**  
Es kommt täglich eine Fehlermeldung

**Expected behavior**  
Was kann ich tun? 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <v1.1.3> aber auch schon früher
 - JS-Controller version: <v16.17.0>

**Comment by inidona** [comment]
Ich hatte das auch, ich habe den Zeitpunkt des Datenladens geändert. Seit dem geht es wieder.
Evtl. gibt es jetzt zuviel Last am server

**Comment by simatec** [comment]
Eine Überlastung der API zu einem bestimmten Zeitpunkt ist durchaus möglich.
Hier hat leider der Adapter keinerlei Einfluss.
