### ISSUE TITLE
Status wurde nach den Ferien nicht zurück auf "false" gesetzt.

### ISSUE THREAD

**Issue by Heisenberg2018** [simatec/ioBroker.schoolfree#263]
**Describe the bug**  
Die Kinder haben mir berichtet dass ihr Licht morgens nicht mehr angeht. 
Ich habe mir das heute angeschaut und gesehen dass bei today und tomorrow der Status immer noch auf true steht. 
Wir wohnen in Schleswig-Holstein und dort sind seit ein paar Tagen gar keine Ferien mehr.

**To Reproduce**  
Das kann ich leider nicht sagen, ich habe mir das eben gerade erst angeschaut.

**Expected behavior**  
Das nach den Ferien wieder der Status auf false gesetzt ist.

**Screenshots & Logfiles**  
Ich sitze jetzt gerade nicht am PC, aber es gab offensichtlich keine verdächtigen Einträge unter Protokolle.
Wie kann ich etwas sehen was helfen kann?

**Versions:**  
 - Adapter version: 1.1.4
 - JS-Controller version: 5.0.19
 - Node version: 18.20.2
 - Operating system: DietPi 64bit (Raspberry Pi 4)

**Additional context**  
Ich habe einfach in den Einstellungen den Name der Schule weggemacht, so dass der Adapter neu lädt, und dann habe ich wieder den Name der Schule angeklickt und noch einmal abgespeichert. 
Jetzt ist der Status wieder korrekt gesetzt, ich werde jetzt beobachten ob es in Zukunft noch einmal Probleme gibt.

**Comment by simatec** [comment]
Setze mal eine andere Zeit für die Abfrage als CronJob. Eventuell ist zu der Standardzeit die API etwas überlastet
