### ISSUE TITLE
Pfingstferien in Niedersachen nicht als Ferientag erkannt

### ISSUE THREAD

**Issue by kschaumann** [simatec/ioBroker.schoolfree#267]
**Describe the bug**  
Heute am 21.05.2024 sind in Niedersachsen Ferien (1. Tag) auch entsprechend [mehr-schulferien.de](https://www.mehr-schulferien.de/ferien/d/bundesland/niedersachsen#mai2024)

![image](https://github.com/simatec/ioBroker.schoolfree/assets/57621623/0a6016ec-825b-48db-b979-9c0ff1def9c0)

Allerdings ist der Status für heute auf "none":

![image](https://github.com/simatec/ioBroker.schoolfree/assets/57621623/8b0f6bd0-da83-417e-87df-a3cb11c55f04)

Entsprechend sind die Rollläden in den Kinderzimmern zur normalen Zeit, nicht zur Ferienzeit gefahren. Was daran liegt, dass der Ferien-Status nicht passt. 

**To Reproduce**  
Konfiguriere den Adapter für Niedersachen und ermittle den Status für heute. 

**Expected behavior**  
Der Status für heute sollte aussagen, dass Ferien sind. 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 800 MHz
Modell: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
RAM: 5.9 GB
System-Betriebszeit: 43 T. 17:33:11
Node.js: v18.19.1
time: 1716269639545
timeOffset: -120
NPM: 10.2.4
Adapter-Anzahl: 537
Datenträgergröße: 15.6 GB
Freier Festplattenspeicher: 7.6 GB
Aktive Instanzen: 37
Pfad: /opt/iobroker/
Betriebszeit: 43 T. 17:33:06
aktiv:

**Additional context**

**Comment by kschaumann** [comment]
Wie es scheint, liegt es auch hier an den Daten: 
[https://github.com/mehr-schulferien-de](https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues/724)

**Comment by hgschiller** [comment]
Hatte das Problem schon Mal mit der Nummer #20 eröffnet.
