### ISSUE TITLE
Herbstferien zu kurz ausgewiesen

### ISSUE THREAD

**Issue by samoht0403** [simatec/ioBroker.schoolfree#300]
**Describe the bug**  
Das Ende der Ferien in BaWü wird für den 30.10. angezeigt, es ist aber der 31.10.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Ich denke,alles zusätzliche wäre nicht interessant, es scheint einfach ein Tag zu fehlen.

**Comment by simatec** [comment]
Bitte ein Issue bei der genutzen API aufmachen. Der Adapter hat hier keinen Einfluss.

https://github.com/mehr-schulferien-de/www.mehr-schulferien.de
