### ISSUE TITLE
info.today and info.tomorrow are writable

### ISSUE THREAD

**Issue by FernetMenta** [simatec/ioBroker.schoolfree#310]
Hi, first I want to thank you for this adapter! Great work.
I was confused about info.today and info.tomorrow, which you call "switches". I wondered what functions I can control by setting those to true or false. Then I looked into the code and found out that those are indicators showing if today or tomorrow are free. Wouldn't it be better to make them read only?

**Comment by simatec** [comment]
thx for your Feedback... Fix with v1.1.7
