### ISSUE TITLE
Feature Request: Additionally support public holidays to determine school holidays

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.schoolfree#4]
It would be great if public holidays would be treated like school holidays.

Just remote the filtering of public holidays by altering one line of code in main
                //const arrOnlyholiday = arrNewHoliday.filter(d => d.starts_on != d.ends_on);
                const arrOnlyholiday = arrNewHoliday;

**Comment by simatec** [comment]
added at release 0.5.0

**Comment by Marty56** [comment]
Gerade getestet. Funktioniert super.
Danke!!

**Comment by simatec** [comment]
Daten komme auch alle wieder?

**Comment by Marty56** [comment]
Ich habe es nur für Bayern getestet. Das wurden aktuelle Coronaschließung und als nächste Ferien Osterferien angezeigt. Das war ok.

**Comment by simatec** [comment]
So ist es bei mir auch aktuell. Sachsen gibt dann aber noch den Karfreitag aus, da die Osterferien dort eine Woche später sind. Voraussetzung ist allerdings, dass die Feiertage nicht ignoriert werden. Im nächsten Schritt will ich mal schauen, dass wir noch mehr Auswahl und nicht nur die Bundesländer bekommen
