### ISSUE TITLE
schoolfree API V2 Änderung

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.schoolfree#8]
Die Entwickler API hat sich aufgrund von Corona geändert und lautet jetzt
url: 'https://www.mehr-schulferien.de/api/v2.0/periods',

Die alte url mit "V1.0" existiert nicht mehr.

**Comment by simatec** [comment]
Danke für die Info. Werde den Adapter heute direkt anpassen

**Comment by simatec** [comment]
Ich habe das gefixt. Allerdings ist die neue API noch Beta und liefert aktuell nur die Daten der aktuellen Ferien.

**Comment by Marty56** [comment]
Danke.

**Comment by Marty56** [comment]
Habe die V 4.01 installiert. Jetzt kommt statt "none"  "no data available".

Ich hätte auch noch eine Frage: Ich hatte mal ein Feature request https://github.com/simatec/ioBroker.schoolfree/issues/4 aufgemacht, auf das ich nie eine Antwort bekommen hatte.

Besteht eine Chance, dass dieses Feature implementiert wird? 

Ich habe mir immer mit einer von mir gepatchten Version behoben und auch das neue API 2.0 jetzt in Form eines eigenen Scripts implementiert. Falls Sie nicht mehr vorhaben, dieses Feature zu implementieren, würde ich bei meiner Lösung bleiben und den Adapter deinstallieren.
Ein Adapter wäre mir natürlich lieber.

**Comment by simatec** [comment]
Aktuell ist die API 2.0 etwas anderes aufgebaut und liefert nicht alle Ferien und Feiertage in der json. Das kann aber auch an der Corona Krise liegen. 
Ich habe mit dem Anbieter bereits Kontakt aufgenommen. 
Die Feiertage zu deiner zweiten Frage kann ich mit  VG integrieren und über das Config Menü wählbar machen.

**Comment by Marty56** [comment]
Das hört sich gut an! 
Hoffentlich wird das Einpflegen der Ferien vom Anbieter weitergeführt.

**Comment by simatec** [comment]
Version 0.5.0 enthält nun wieder alle Daten

**Comment by simatec** [comment]
Wenn du Zeit und Lust hast, dann teste mal die Beta 0.5.1 vom Github.
Es gibt neue Features ...

**Comment by Marty56** [comment]
Ich habe die Version installiert und bei der Installation eine Fehlermeldung
`
schoolfree.0 | 2020-03-26 04:04:51.057 | info | (30075) terminating
-- | -- | -- | --
schoolfree.0 | 2020-03-26 04:04:50.423 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
schoolfree.0 | 2020-03-26 04:04:50.423 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
schoolfree.0 | 2020-03-26 04:04:50.423 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
schoolfree.0 | 2020-03-26 04:04:50.423 | error | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:572:33)
schoolfree.0 | 2020-03-26 04:04:50.423 | error | at adapter.getState (/opt/iobroker/node_modules/iobroker.schoolfree/main.js:233:28)
schoolfree.0 | 2020-03-26 04:04:50.423 | error | (30075) TypeError: Cannot read property 'val' of null
schoolfree.0 | 2020-03-26 04:04:50.421 | error | (30075) uncaught exception: Cannot read property 'val' of null
schoolfree.0 | 2020-03-26 04:04:48.570 | info | (30075) starting. Version 0.5.1 in /opt/iobroker/node_modules/iobroker.schoolfree, node: v10.17.0
host.ioBroker-RasPi4 | 2020-03-26 04:04:39.700 | info | instance system.adapter.schoolfree.0 started with pid 30075
host.ioBroker-RasPi4 | 2020-03-26 04:04:39.650 | info | instance scheduled system.adapter.schoolfree.0 1 0 * * *
`
Dann habe ich das Land und den Ort festgelegt (unsere Schule war in der Liste nicht vorhanden). Danach hat der Adapter dieselben Daten geliefert wie vorher.

Mir ist nicht so ganz klar, warum man Land, Ort und Schule jetzt festlegen soll. So unterschiedlich sind die Ferientag nicht.

**Comment by simatec** [comment]
Hier geht es darum, dass teilweise Ferien, Feiertage und auch bewegliche Ferientage nicht Bundeslandbezogen sind, sondern teilweise auf Landkreise oder auch Schulen bezogen sind.

Den Bug schaue ich mir gleich mal an, Grundsätzlich ist es aber so aufgebaut, dass du nur das Bundesland wählen musst.. Der Rest ist optional

**Comment by Marty56** [comment]
Danke für die Erläuterung.
Nochmal zu dem Bug. Er kam nur einmal direkt nach der Installation! Ich hatte noch von der vorigen Version nur das Bundesland konfiguriert.

**Comment by simatec** [comment]
Damit hatte es nix zu tun. War mein Fehler im Code. Ist jetzt aber behoben. Zum testen kannst du ja mal updaten und vorher den kompletten Ordner schoolfree.0 löschen. 
Dann sollte auch beim ersten Start kein Fehler mehr kommen.

**Comment by Marty56** [comment]
Habe getestet. Sieht gut aus. Keine Fehler mehr!

**Comment by simatec** [comment]
sehr gut ... test mal bitte noch ein wenig ... wenn bei dir ebenfalls alles gut läuft, kann ich die Version ins npm pushen
